app:
    resource: '@AppBundle/Controller/'
    type: annotation



root:
    path: /
    defaults:
            _controller: FrameworkBundle:Redirect:redirect
            route: homepage
            permanent: true




errors:
    resource: "@TwigBundle/Resources/config/routing/errors.xml"
    prefix:   /error